services:
  bet-service:
    build: .
    image: bet-service
    container_name: bet-service
    ports:
      - "8000:8000"
    environment:
      ServerPort: "8000"
    volumes:
      - ./data:/data
  geoipupdate:
    image: maxmindinc/geoipupdate
    container_name: geoipupdate
    environment:
      GEOIPUPDATE_FREQUENCY: 24
      GEOIPUPDATE_ACCOUNT_ID: 777155
      GEOIPUPDATE_LICENSE_KEY: HhJ3cMvkJxbo3NGN
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country
    volumes:
      - /geoip:/usr/share/GeoIP maxmindinc/geoipupdate
