services:
  bet-service-4:
    build: .
    image: bet-service
    container_name: bet-service-4
    ports:
      - "8003:8003"
    environment:
      ServerPort: "8003"
    volumes:
      - ./data4:/data
      - geoip:/geoip
  geoipupdate:
    image: maxmindinc/geoipupdate
    container_name: geoipupdate
    environment:
      GEOIPUPDATE_FREQUENCY: 24
      GEOIPUPDATE_ACCOUNT_ID: 777155
      GEOIPUPDATE_LICENSE_KEY: HhJ3cMvkJxbo3NGN
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country
    volumes:
      - geoip:/usr/share/GeoIP maxmindinc/geoipupdate

volumes:
  geoip:
